version: '3'

networks:
  eventmanager-net:

services:
  # Include all services from docker-compose.yaml
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "8080:443"
    depends_on:
      - events_db
      - events_api
      - events_web
      - tickets_db
      - tickets_api
      - tickets_web
      - auth_db
      - auth_api
      - auth_web
      - review_api
      - review_web
      - notification_api
      - notification_web
      - notification_db
    networks:
      - eventmanager-net

  events_db:
    image: mysql:latest
    volumes:
      - events-mysql-data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_DATABASE: ${EVENTS_MYSQL_DATABASE}
      MYSQL_USER: ${EVENTS_MYSQL_USER}
      MYSQL_PASSWORD: ${EVENTS_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${EVENTS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE_PORT: ${EVENTS_MYSQL_DATABASE_PORT}
    networks:
      - eventmanager-net
    healthcheck:
      test: 'echo "select now(); " | mysql -h ${EVENTS_MYSQL_HOST} -u${EVENTS_MYSQL_USER} -p${EVENTS_MYSQL_PASSWORD}'
      interval: 1s
      retries: 10
      start_period: 10s
      timeout: 1s

  events_api:
    image: registry.gitlab.com/kavalarj/eventmanager/events_api:latest
    depends_on:
      events_db:
        condition: service_healthy
    env_file: .env
    environment:
      ALLOWED_HOSTS: '*'
    working_dir: "/app"
    networks:
      - eventmanager-net

  events_web:
    image: registry.gitlab.com/kavalarj/eventmanager/events_web:latest
    depends_on:
      events_api:
        condition: service_healthy
    env_file: .env
    environment:
      REACT_APP_API_URL: http://events_api:8000
    networks:
      - eventmanager-net

  tickets_db:
    image: mysql:latest
    volumes:
      - tickets-mysql-data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_DATABASE: ${TICKETS_MYSQL_DATABASE}
      MYSQL_USER: ${TICKETS_MYSQL_USER}
      MYSQL_PASSWORD: ${TICKETS_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${TICKETS_MYSQL_ROOT_PASSWORD}
    networks:
      - eventmanager-net
    healthcheck:
      test: 'echo "select now(); " | mysql -h ${TICKETS_MYSQL_HOST} -u${TICKETS_MYSQL_USER} -p${TICKETS_MYSQL_PASSWORD}'
      interval: 1s
      retries: 10
      start_period: 10s
      timeout: 1s

  tickets_api:
    image: registry.gitlab.com/kavalarj/eventmanager/tickets_api:latest
    depends_on:
      tickets_db:
        condition: service_healthy
    env_file: .env
    environment:
      ALLOWED_HOSTS: '*'
    working_dir: "/app"
    networks:
      - eventmanager-net

  tickets_web:
    image: registry.gitlab.com/kavalarj/eventmanager/tickets_web:latest
    depends_on:
      tickets_api:
        condition: service_healthy
    env_file: .env
    environment:
      REACT_APP_API_URL: http://tickets_api:8000
    networks:
      - eventmanager-net

  auth_db:
    image: mysql:latest
    volumes:
      - auth-mysql-data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_DATABASE: ${AUTH_MYSQL_DATABASE}
      MYSQL_USER: ${AUTH_MYSQL_USER}
      MYSQL_PASSWORD: ${AUTH_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${AUTH_MYSQL_ROOT_PASSWORD}
    networks:
      - eventmanager-net
    healthcheck:
      test: 'echo "select now(); " | mysql -h ${AUTH_MYSQL_HOST} -u${AUTH_MYSQL_USER} -p${AUTH_MYSQL_PASSWORD}'
      interval: 1s
      retries: 10
      start_period: 10s
      timeout: 1s

  auth_api:
    image: registry.gitlab.com/kavalarj/eventmanager/auth_api:latest
    depends_on:
      auth_db:
        condition: service_healthy
    env_file: .env
    environment:
      ALLOWED_HOSTS: '*'
    working_dir: "/app"
    networks:
      - eventmanager-net

  auth_web:
    image: registry.gitlab.com/kavalarj/eventmanager/auth_web:latest
    depends_on:
      auth_api:
        condition: service_healthy
    env_file: .env
    environment:
      REACT_APP_API_URL: http://auth_api:8000
    networks:
      - eventmanager-net

  review_api:
    image: registry.gitlab.com/kavalarj/eventmanager/review_api:latest
    depends_on:
      events_api:
        condition: service_healthy
    env_file: .env
    environment:
      ALLOWED_HOSTS: '*'
    working_dir: "/app"
    networks:
      - eventmanager-net

  review_web:
    image: registry.gitlab.com/kavalarj/eventmanager/review_web:latest
    depends_on:
      review_api:
        condition: service_healthy
    env_file: .env
    environment:
      REACT_APP_API_URL: http://review_api:8000
    networks:
      - eventmanager-net

  notification_db:
    image: mysql:latest
    volumes:
      - notification-mysql-data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_DATABASE: ${NOTIFICATION_MYSQL_DATABASE}
      MYSQL_USER: ${NOTIFICATION_MYSQL_USER}
      MYSQL_PASSWORD: ${NOTIFICATION_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${NOTIFICATION_MYSQL_ROOT_PASSWORD}
    networks:
      - eventmanager-net
    healthcheck:
      test: 'echo "select now(); " | mysql -h ${NOTIFICATION_MYSQL_HOST} -u${NOTIFICATION_MYSQL_USER} -p${NOTIFICATION_MYSQL_PASSWORD}'
      interval: 1s
      retries: 10
      start_period: 10s
      timeout: 1s

  notification_api:
    image: registry.gitlab.com/kavalarj/eventmanager/notification_api:latest
    depends_on:
      notification_db:
        condition: service_healthy
    env_file: .env
    environment:
      ALLOWED_HOSTS: '*'
    working_dir: "/app"
    networks:
      - eventmanager-net

  notification_web:
    image: registry.gitlab.com/kavalarj/eventmanager/notification_web:latest
    depends_on:
      notification_api:
        condition: service_healthy
    env_file: .env
    environment:
      REACT_APP_API_URL: http://notification_api:8000
    networks:
      - eventmanager-net

  integration_test:
    build:
      context: ./Integration_Tests
      dockerfile: ./docker/Dockerfile
    depends_on:
      nginx:
        condition: service_healthy
      events_api:
        condition: service_healthy
      tickets_api:
        condition: service_healthy
      auth_api:
        condition: service_healthy
      review_api:
        condition: service_healthy
      notification_api:
        condition: service_healthy
    working_dir: /app
    command: >
      sh -c "python test_app.py"
    networks:
      - eventmanager-net

volumes:
  events-mysql-data:
  tickets-mysql-data:
  auth-mysql-data:
  notification-mysql-data: