volumes:
  events-mysql-data:
  events-fast-data:
  tickets-fast-data:
  tickets-mysql-data:

networks:
  eventmanager-net:

services:

# CONTAINERS - EVENTS
  events_db:
    image: mysql:latest
    
    volumes:
      - events-mysql-data:/var/lib/mysql
    
    env_file: .env
    environment:
      MYSQL_DATABASE: ${EVENTS_MYSQL_DATABASE}
      MYSQL_USER: ${EVENTS_MYSQL_USER}
      MYSQL_PASSWORD: ${EVENTS_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${EVENTS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE_PORT: ${EVENTS_MYSQL_DATABASE_PORT}

    networks:
      - eventmanager-net

    healthcheck:
       test: 'echo "select now(); " | mysql -h ${EVENTS_MYSQL_HOST} -u${EVENTS_MYSQL_USER} -p${EVENTS_MYSQL_PASSWORD}'
       interval: 1s
       retries: 10
       start_period: 10s
       timeout: 1s

    ports:
    - "3306"

  events_api:
    build:
      context: ../Events
      dockerfile: ../Events/DockerFile
    
    volumes:
    - events-fast-data:/media
    - ../Events/src:/app

    depends_on:
      events_db:
        condition: service_healthy

    env_file: .env
    environment:
      ALLOWED_HOSTS: '*'

    working_dir: "/app"
    
    ports:
    - "8000:8000"

    command: >
      sh -c "python test.py && 
             exec uvicorn main:app --host 0.0.0.0 --reload"

    networks:
    - eventmanager-net

  events_web:
    build: ../Events/eventsSvelte

    ports:
     - "8001:5173"

    volumes:
      - ../Events/eventsSvelte:/app #Hot-reload
      - /app/node_modules

    networks:
      - eventmanager-net

# CONTAINERS - TICKETS
  tickets_db:
    image: mysql:latest

    volumes:
      - tickets-mysql-data:/var/lib/mysql

    env_file: .env

    environment:
      MYSQL_DATABASE: ${TICKETS_MYSQL_DATABASE}
      MYSQL_USER: ${TICKETS_MYSQL_USER}
      MYSQL_PASSWORD: ${TICKETS_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${TICKETS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE_PORT: ${TICKETS_MYSQL_DATABASE_PORT}

    networks:
      - eventmanager-net

    healthcheck:
      test: 'echo "select now();" | mysql -h ${TICKETS_MYSQL_DATABASE_HOST} -u${TICKETS_MYSQL_USER} -p${TICKETS_MYSQL_PASSWORD}'
      interval: 1s
      retries: 10
      start_period: 10s
      timeout: 1s

  tickets_api:
    build:
      context: ../Tickets
      dockerfile: ../Tickets/docker/fastapi/Dockerfile

    env_file: .env

    restart: always
    
    volumes:
    - tickets-fast-data:/media
    - ../Tickets/src_fastapi:/app

    ports:
      - "8000"

    depends_on:
      tickets_db:
        condition: service_healthy

    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

    networks:
      - eventmanager-net
  
  tickets_web:
    build:
      context: ../Tickets
      dockerfile: ../Tickets/docker/sveltekit/Dockerfile

    ports:
      - "8002:5173"

    volumes:
      - ../Tickets/src_svelte_frontend:/app #Hot-reload
      - /app/node_modules

    depends_on:
      - tickets_api

    networks:
      - eventmanager-net