networks:
  my-network:
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:

  api:
    container_name: ReviewAPI
    build:
      dockerfile: ./src/Dockerfile
    
    ports:
    - "8083:8000"

    # command: >
    #   sh -c "pytest && 
    #          exec uvicorn main:app --host 0.0.0.0 --reload"

    networks:
    - my-network
    extra_hosts:
      - "api:192.168.1.1"

  frontend:
    container_name: ReviewFrontend
    build:
      dockerfile: ./frontend/Dockerfile
    
    ports:
    - "5000:5000"

    networks:
    - my-network