networks:
  my-network:

services:

  api:
    container_name: ReviewAPI
    build:
      dockerfile: ./src/Dockerfile

    volumes:
    - ./src:/app

    working_dir: "/app"
    
    ports:
    - "8083:8000"

    command: >
      sh -c "pytest && 
             exec uvicorn main:app --host 0.0.0.0 --reload"

    networks:
    - my-network

  frontend:
    container_name: ReviewFrontend
    build:
      dockerfile: ./frontend/Dockerfile

    volumes:
    - ./frontend:/app

    working_dir: "/app"
    
    ports:
    - "3000:3000"

    networks:
    - my-network