networks:
  my-network:

services:

  api:
    container_name: ReviewAPI

    build:
      dockerfile: ./src/Dockerfile

    ports:
    - "8083:8000"

    command: >
      sh -c "exec uvicorn main:app --host 0.0.0.0 --reload"

    networks:
    - my-network

  frontend:
    container_name: ReviewFrontend

    build:
      dockerfile: ./frontend/Dockerfile
    
    ports:
    - "5000:5000"

    networks:
    - my-network