networks:
  my-network:

services:

  api:
    container_name: ReviewAPI

    build:
      dockerfile: ./backend/Dockerfile

    ports:
    - "8083:8000"

    command: >
      sh -c "exec uvicorn main:app --host 0.0.0.0 --reload"

    networks:
    - my-network

  frontend:
    container_name: ReviewFrontend

    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:80"
    networks:
      - my-network