# Config file for Air
[build]
  cmd = "go build -o main main.go"
  bin = "main"
  dir = "."
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp"]
  run_after_build = "chmod +x main"

[log]
  level = "debug"