name: Build, Test, and Push Docker Images

on:
  push:
    branches: [ "CI/CD" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        run: docker-compose -f docker-compose.yaml build
        env:
          EVENTS_MYSQL_DATABASE: EventManagement
          EVENTS_MYSQL_USER: db_user
          EVENTS_MYSQL_PASSWORD: db_pw
          EVENTS_MYSQL_ROOT_PASSWORD: db_pw
          EVENTS_MYSQL_DATABASE_PORT: 3306
          EVENTS_MYSQL_HOST: events_db
          TICKETS_MYSQL_DATABASE: tickets_db
          TICKETS_MYSQL_USER: db_user
          TICKETS_MYSQL_PASSWORD: db_pw
          TICKETS_MYSQL_ROOT_PASSWORD: db_pw
          TICKETS_MYSQL_DATABASE_HOST: tickets_db
          TICKETS_MYSQL_DATABASE_PORT: 3306

      - name: Test
        run: docker-compose -f docker-compose.yaml run events_api python test.py
        env:
          EVENTS_MYSQL_DATABASE: EventManagement
          EVENTS_MYSQL_USER: db_user
          EVENTS_MYSQL_PASSWORD: db_pw
          EVENTS_MYSQL_ROOT_PASSWORD: db_pw
          EVENTS_MYSQL_DATABASE_PORT: 3306
          EVENTS_MYSQL_HOST: events_db
          TICKETS_MYSQL_DATABASE: tickets_db
          TICKETS_MYSQL_USER: db_user
          TICKETS_MYSQL_PASSWORD: db_pw
          TICKETS_MYSQL_ROOT_PASSWORD: db_pw
          TICKETS_MYSQL_DATABASE_HOST: tickets_db
          TICKETS_MYSQL_DATABASE_PORT: 3306

      # Log in to GitLab registry
      - name: Log in to GitLab Registry
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Push images
        run: docker-compose -f docker-compose.yaml push
        env:
          EVENTS_MYSQL_DATABASE: EventManagement
          EVENTS_MYSQL_USER: db_user
          EVENTS_MYSQL_PASSWORD: db_pw
          EVENTS_MYSQL_ROOT_PASSWORD: db_pw
          EVENTS_MYSQL_DATABASE_PORT: 3306
          EVENTS_MYSQL_HOST: events_db
          TICKETS_MYSQL_DATABASE: tickets_db
          TICKETS_MYSQL_USER: db_user
          TICKETS_MYSQL_PASSWORD: db_pw
          TICKETS_MYSQL_ROOT_PASSWORD: db_pw
          TICKETS_MYSQL_DATABASE_HOST: tickets_db
          TICKETS_MYSQL_DATABASE_PORT: 3306