# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    paths:
      - 'Payment/**'
  pull_request:
    paths:
      - 'Payment/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('Payment/src/api/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      working-directory: Payment/src/api
      run: go build -v ./...

    - name: Test
      working-directory: Payment/src/api
      run: go test -v ./...